name: compile-test-actions
on: [pull_request]
jobs:
  # compile-out-of-container:
  #   runs-on: ubuntu-latest
  #   steps:
  #     #- name: install Docker
  #     #  run: |
  #     #    sudo apt-get update
  #     #    sudo apt install snap
  #     #    sudo snap install docker

  #     - name: Download this repo
  #       uses: actions/checkout@v3
  #     - name: Setup docker images
  #       run: sudo bash ./scripts/dockersetup.sh
  #     - name: compile the contents
  #       run: sudo bash ./scripts/compile.sh
  compile-inside-container:
    runs-on: ubuntu-latest
    container: 
      image: eisverygoodletter/debian-stretch-cross:bluetooth
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with: 
          path: ./
      - name: compile it
        run: |
          tree ~
          sudo chmod +x ./scripts/runWithinContainer.sh
          sudo bash ./scripts/runWithinContainer.sh -w
        shell: bash
