name: compile-test-actions
on: [push, pull_request]
jobs:
  inside-container-job:
    runs-on: ubuntu-latest
    container: 
      image: ev3dev/debian-stretch-cross:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
        with: 
          path: main
      - name: compile it
        run: |
          cd main
          sudo chmod +x ./scripts/runWithinContainer.sh
          sudo bash ./scripts/runWithinContainer.sh
        shell: bash
